#!/usr/bin/env python3
# Copyright 2024 Kevin Medrano
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Multi-Axis Slicer — CLI tool for non-planar robotic 3D printing.

Unlike conventional slicers that produce flat horizontal layers, this slicer
generates G-code with per-waypoint nozzle orientation annotations.  The robot
arm tilts the extruder to follow surface normals, enabling:

  - Overhang printing without support material
  - Smoother surfaces via conformal layer deposition

Output G-code contains standard moves (G0/G1) with extended ORIENT comments
that the print_node parses to set robot tool orientation at each waypoint::

    G1 X10.0 Y20.0 Z5.0 F3000 E0.50 ; ORIENT nx=0.00 ny=0.10 nz=-0.99

Usage:
    python3 multiaxis_slicer.py model.stl -o model_multiaxis.gcode
    python3 multiaxis_slicer.py model.stl --layer-height 0.5 --max-tilt 45
"""

import argparse
import os
import sys

import numpy as np

# Allow running this script from the resource/ directory or as an installed
# package.  When run directly, the parent package must be on sys.path.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from ur_3d_printer.multiaxis_planner import (  # noqa: E402
    MultiAxisConfig,
    MultiAxisToolpathGenerator,
)
from ur_3d_printer.collision_checker import SelfCollisionChecker  # noqa: E402


def _toolpath_to_gcode(
    toolpath,
    print_speed: float = 50.0,
    travel_speed: float = 150.0,
    source: str = '',
) -> str:
    """Convert a Toolpath object to multi-axis annotated G-code."""
    lines = [
        '; Multi-axis G-code generated by multiaxis_slicer.py',
        f'; Source: {source}',
        f'; Layers: {toolpath.num_layers}',
        f'; Waypoints: {toolpath.num_waypoints}',
        '; Nozzle orientation encoded in ORIENT comments',
        ';',
        'G90 ; Absolute positioning',
        'G21 ; Millimetres',
        'M82 ; Absolute extrusion',
        'M104 S210 ; Hotend temperature',
        'M140 S60  ; Bed temperature',
        'M109 S210 ; Wait for hotend',
        'M190 S60  ; Wait for bed',
        'G28 ; Home',
        ';',
    ]

    feed_print = print_speed * 60.0   # mm/min
    feed_travel = travel_speed * 60.0
    e_total = 0.0

    for layer in toolpath.layers:
        z_mm = layer.z_height * 1000.0
        lines.append(';')
        # Emit planar-compatible layer markers so the web viewer's parser
        # picks up layer boundaries the same way for both slicers.
        lines.append(f'; LAYER:{layer.index}')
        lines.append(f'; Z:{z_mm:.3f}')

        emitted_infill_marker = False
        for i, wp in enumerate(layer.waypoints):
            x_mm = wp.position[0] * 1000.0
            y_mm = wp.position[1] * 1000.0
            z_mm = wp.position[2] * 1000.0

            # First infill waypoint of the layer: emit the section marker so
            # downstream parsers can colour fill vs wall separately.
            if wp.is_infill and not emitted_infill_marker:
                lines.append('; INFILL:multiaxis')
                emitted_infill_marker = True

            approach = wp.orientation[:, 2]
            orient = (
                f' ; ORIENT nx={approach[0]:.4f}'
                f' ny={approach[1]:.4f}'
                f' nz={approach[2]:.4f}'
            )

            if wp.is_travel:
                lines.append(
                    f'G0 X{x_mm:.3f} Y{y_mm:.3f} Z{z_mm:.3f}'
                    f' F{feed_travel:.0f}{orient}'
                )
            else:
                if i > 0:
                    prev = layer.waypoints[i - 1]
                    d = float(np.linalg.norm(
                        wp.position - prev.position,
                    )) * 1000.0
                    e_total += d * 0.04  # simplified extrusion factor
                lines.append(
                    f'G1 X{x_mm:.3f} Y{y_mm:.3f} Z{z_mm:.3f}'
                    f' F{feed_print:.0f} E{e_total:.4f}{orient}'
                )

    lines += [
        ';',
        '; End',
        'M104 S0 ; Hotend off',
        'M140 S0 ; Bed off',
        'G0 Z100 F3000 ; Raise nozzle',
        'G28 X Y ; Home XY',
        'M84 ; Motors off',
    ]
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(
        description='Multi-axis slicer for robotic 3D printing',
    )
    parser.add_argument('stl_file', help='Input STL file')
    parser.add_argument(
        '-o', '--output', default=None,
        help='Output G-code file (default: <input>_multiaxis.gcode)',
    )
    parser.add_argument(
        '--layer-height', type=float, default=0.5,
        help='Layer height in mm (default: 0.5)',
    )
    parser.add_argument(
        '--max-tilt', type=float, default=45.0,
        help='Maximum nozzle tilt in degrees (default: 45)',
    )
    parser.add_argument(
        '--print-speed', type=float, default=50.0,
        help='Print speed in mm/s (default: 50)',
    )
    parser.add_argument(
        '--travel-speed', type=float, default=150.0,
        help='Travel speed in mm/s (default: 150)',
    )
    parser.add_argument(
        '--robot', default='ur5e',
        choices=['ur3e', 'ur5e', 'ur7e', 'ur10e'],
        help='Robot model for collision checking (default: ur5e)',
    )
    parser.add_argument(
        '--no-collision-check', action='store_true',
        help='Disable self-collision checking',
    )
    args = parser.parse_args()

    if args.output is None:
        base = os.path.splitext(args.stl_file)[0]
        args.output = base + '_multiaxis.gcode'

    print(f'Slicing {args.stl_file} ...', file=sys.stderr)
    print(f'  Layer height : {args.layer_height} mm', file=sys.stderr)
    print(f'  Max tilt     : {args.max_tilt} deg', file=sys.stderr)
    print(f'  Robot model  : {args.robot}', file=sys.stderr)
    print(f'  Collision chk: {not args.no_collision_check}', file=sys.stderr)

    config = MultiAxisConfig(
        layer_height=args.layer_height / 1000.0,   # mm → m
        max_tilt_angle=np.radians(args.max_tilt),
        enable_collision_check=(not args.no_collision_check),
        robot_model=args.robot,
        print_speed=args.print_speed / 1000.0,     # mm/s → m/s
        travel_speed=args.travel_speed / 1000.0,
    )

    gen = MultiAxisToolpathGenerator(config)
    toolpath = gen.generate_from_stl(args.stl_file)

    gcode = _toolpath_to_gcode(
        toolpath,
        print_speed=args.print_speed,
        travel_speed=args.travel_speed,
        source=os.path.basename(args.stl_file),
    )

    with open(args.output, 'w') as f:
        f.write(gcode)

    print(f'\nMulti-axis slicing complete:', file=sys.stderr)
    print(f'  Layers    : {toolpath.num_layers}', file=sys.stderr)
    print(f'  Waypoints : {toolpath.num_waypoints}', file=sys.stderr)
    print(f'  Output    : {args.output}', file=sys.stderr)

    est = toolpath.estimated_time
    if est > 0:
        print(
            f'  Est. time : {est / 60.0:.1f} min @ {args.print_speed} mm/s',
            file=sys.stderr,
        )


if __name__ == '__main__':
    main()
