# Copyright 2024 Kevin Medrano
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
G-code Parser

Parses standard FDM G-code into Toolpath data structures.
Supports G0/G1 (linear), G2/G3 (arcs), G28 (home), G90/G91 (abs/rel),
G92 (set position), M82/M83 (extrusion mode), M104/M109 (temp), M106/M107 (fan).

Converts mm → meters, mm/min → m/s during parsing.
No ROS dependencies.
"""

import math
import re
from typing import Dict, List, Optional
import numpy as np

from .toolpath import Waypoint, Layer, Toolpath


# Conversion constants
MM_TO_M = 0.001
MM_PER_MIN_TO_M_PER_S = MM_TO_M / 60.0


class GCodeParser:
    """Parse G-code files into Toolpath objects.

    Args:
        filament_diameter: Filament diameter in mm (for volumetric rate calc).
        arc_resolution: Arc discretization segment length in mm.
        layer_z_threshold: Minimum Z change in mm to detect a new layer.
        default_feed_rate: Default feed rate in mm/min if not specified.
    """

    def __init__(
        self,
        filament_diameter: float = 1.75,
        arc_resolution: float = 1.0,
        layer_z_threshold: float = 0.1,
        default_feed_rate: float = 1200.0,
    ):
        self.filament_diameter = filament_diameter
        self.filament_area = math.pi * (filament_diameter / 2.0) ** 2  # mm^2
        self.arc_resolution = arc_resolution
        self.layer_z_threshold = layer_z_threshold
        self.default_feed_rate = default_feed_rate

        # Parser state
        self._reset_state()

    def _reset_state(self):
        """Reset parser state for a new file."""
        self.absolute_positioning = True
        self.absolute_extrusion = True
        self.current_x = 0.0  # mm
        self.current_y = 0.0  # mm
        self.current_z = 0.0  # mm
        self.current_e = 0.0  # mm (filament length)
        self.current_f = self.default_feed_rate  # mm/min
        self.current_layer = 0
        self.last_z = 0.0  # mm
        self.temperatures: Dict[str, float] = {}

    def parse_file(self, filepath: str) -> Toolpath:
        """Parse a G-code file into a Toolpath.

        Args:
            filepath: Path to the .gcode file.

        Returns:
            Toolpath object with all parsed layers/waypoints.
        """
        with open(filepath, 'r') as f:
            lines = f.readlines()
        return self.parse_lines(lines)

    def parse_lines(self, lines: List[str]) -> Toolpath:
        """Parse G-code lines into a Toolpath.

        Args:
            lines: List of G-code lines.

        Returns:
            Toolpath object.
        """
        self._reset_state()
        waypoints: List[Waypoint] = []
        metadata: Dict[str, any] = {}

        for line_num, line in enumerate(lines, start=1):
            line = line.strip()
            if not line or line.startswith(';'):
                # Check for metadata in comments
                self._parse_comment(line, metadata)
                continue

            # Strip inline comments
            comment_idx = line.find(';')
            comment = ''
            if comment_idx >= 0:
                comment = line[comment_idx:]
                line = line[:comment_idx].strip()

            if not line:
                self._parse_comment(comment, metadata)
                continue

            # Parse the G-code command
            parsed = self._parse_line(line, line_num, comment)
            if parsed is not None:
                waypoints.extend(parsed)

        # Organize waypoints into layers
        toolpath = self._build_toolpath(waypoints, metadata)
        return toolpath

    def _parse_comment(self, comment: str, metadata: Dict):
        """Extract metadata from comments."""
        if not comment:
            return
        comment = comment.lstrip(';').strip()

        # Check for orientation metadata (for non-planar)
        if comment.startswith('ORIENT:'):
            # Future: parse orientation data
            pass

        # Common slicer metadata
        for prefix in (
            'Generated by', 'Slicer', 'Filament', 'Layer height',
            'Print time', 'Material'
        ):
            if comment.lower().startswith(prefix.lower()):
                key = prefix.lower().replace(' ', '_')
                metadata[key] = comment[len(prefix):].strip().lstrip(':').strip()

    def _parse_line(self, line: str, line_num: int, comment: str = '') -> Optional[List[Waypoint]]:
        """Parse a single G-code line.

        Returns list of waypoints (may be empty or multiple for arcs).
        """
        parts = line.upper().split()
        if not parts:
            return None

        cmd = parts[0]
        params = self._parse_params(parts[1:])

        if cmd in ('G0', 'G00'):
            return self._handle_linear_move(params, line_num, is_rapid=True)
        elif cmd in ('G1', 'G01'):
            return self._handle_linear_move(params, line_num, is_rapid=False)
        elif cmd in ('G2', 'G02'):
            return self._handle_arc(params, line_num, clockwise=True)
        elif cmd in ('G3', 'G03'):
            return self._handle_arc(params, line_num, clockwise=False)
        elif cmd in ('G28',):
            return self._handle_home(params, line_num)
        elif cmd in ('G90',):
            self.absolute_positioning = True
        elif cmd in ('G91',):
            self.absolute_positioning = False
        elif cmd in ('G92',):
            self._handle_set_position(params)
        elif cmd in ('M82',):
            self.absolute_extrusion = True
        elif cmd in ('M83',):
            self.absolute_extrusion = False
        elif cmd in ('M104', 'M109'):
            if 'S' in params:
                self.temperatures['hotend'] = params['S']
        elif cmd in ('M140', 'M190'):
            if 'S' in params:
                self.temperatures['bed'] = params['S']
        elif cmd in ('M106',):
            if 'S' in params:
                self.temperatures['fan'] = params['S']
        elif cmd in ('M107',):
            self.temperatures['fan'] = 0.0

        return None

    def _parse_params(self, parts: List[str]) -> Dict[str, float]:
        """Parse G-code parameters like X10.5 Y20.3 into dict."""
        params = {}
        for part in parts:
            if not part:
                continue
            match = re.match(r'([A-Z])(-?[\d.]+)', part)
            if match:
                params[match.group(1)] = float(match.group(2))
        return params

    def _handle_linear_move(
        self, params: Dict[str, float], line_num: int, is_rapid: bool
    ) -> List[Waypoint]:
        """Handle G0/G1 linear move."""
        # Update feed rate if specified
        if 'F' in params:
            self.current_f = params['F']

        # Calculate target position
        if self.absolute_positioning:
            target_x = params.get('X', self.current_x)
            target_y = params.get('Y', self.current_y)
            target_z = params.get('Z', self.current_z)
        else:
            target_x = self.current_x + params.get('X', 0.0)
            target_y = self.current_y + params.get('Y', 0.0)
            target_z = self.current_z + params.get('Z', 0.0)

        # Calculate extrusion
        e_delta = 0.0
        if 'E' in params:
            if self.absolute_extrusion:
                e_delta = params['E'] - self.current_e
                self.current_e = params['E']
            else:
                e_delta = params['E']
                self.current_e += params['E']

        # Detect layer change
        z_change = abs(target_z - self.last_z)
        if z_change > self.layer_z_threshold and target_z > self.last_z:
            self.current_layer += 1
            self.last_z = target_z

        # Determine if travel (no extrusion or rapid)
        is_travel = is_rapid or e_delta <= 0.0

        # Compute feed rate in m/s
        feed_rate = self.current_f * MM_PER_MIN_TO_M_PER_S

        # Compute volumetric extrusion rate (m^3/s)
        extrusion_rate = 0.0
        if e_delta > 0.0:
            # Distance of this move in mm
            dx = target_x - self.current_x
            dy = target_y - self.current_y
            dz = target_z - self.current_z
            move_dist = math.sqrt(dx * dx + dy * dy + dz * dz)

            if move_dist > 0.0:
                # Filament volume extruded = e_delta * filament_area (mm^3)
                # Time for move = move_dist / feed_rate_mm_per_s
                # Rate = volume / time = (e_delta * area) / (dist / speed)
                #      = e_delta * area * speed / dist
                feed_mm_per_s = self.current_f / 60.0
                volume_mm3 = e_delta * self.filament_area
                move_time = move_dist / feed_mm_per_s if feed_mm_per_s > 0 else 0.0
                if move_time > 0:
                    extrusion_rate = (volume_mm3 * 1e-9) / move_time  # mm^3 → m^3

        # Update current position
        self.current_x = target_x
        self.current_y = target_y
        self.current_z = target_z

        # Create waypoint (convert mm to meters)
        wp = Waypoint(
            position=np.array([
                target_x * MM_TO_M,
                target_y * MM_TO_M,
                target_z * MM_TO_M,
            ]),
            feed_rate=feed_rate,
            extrusion_rate=extrusion_rate,
            is_travel=is_travel,
            layer_index=self.current_layer,
            line_number=line_num,
        )

        return [wp]

    def _handle_arc(
        self, params: Dict[str, float], line_num: int, clockwise: bool
    ) -> List[Waypoint]:
        """Handle G2/G3 arc move by discretizing into line segments."""
        if 'F' in params:
            self.current_f = params['F']

        # Target position
        if self.absolute_positioning:
            target_x = params.get('X', self.current_x)
            target_y = params.get('Y', self.current_y)
        else:
            target_x = self.current_x + params.get('X', 0.0)
            target_y = self.current_y + params.get('Y', 0.0)

        target_z = params.get('Z', self.current_z)

        # Arc center offset (I, J relative to current position)
        i_offset = params.get('I', 0.0)
        j_offset = params.get('J', 0.0)

        center_x = self.current_x + i_offset
        center_y = self.current_y + j_offset

        # Calculate arc geometry
        start_angle = math.atan2(
            self.current_y - center_y, self.current_x - center_x
        )
        end_angle = math.atan2(
            target_y - center_y, target_x - center_x
        )
        radius = math.sqrt(i_offset ** 2 + j_offset ** 2)

        if radius < 1e-6:
            # Degenerate arc, treat as linear
            self.current_x = target_x
            self.current_y = target_y
            self.current_z = target_z
            return self._handle_linear_move(params, line_num, is_rapid=False)

        # Calculate sweep angle
        if clockwise:
            sweep = start_angle - end_angle
            if sweep <= 0:
                sweep += 2.0 * math.pi
        else:
            sweep = end_angle - start_angle
            if sweep <= 0:
                sweep += 2.0 * math.pi

        # Discretize arc
        arc_length = radius * sweep  # mm
        num_segments = max(2, int(arc_length / self.arc_resolution))

        # Extrusion per segment
        e_delta_total = 0.0
        if 'E' in params:
            if self.absolute_extrusion:
                e_delta_total = params['E'] - self.current_e
                self.current_e = params['E']
            else:
                e_delta_total = params['E']
                self.current_e += params['E']

        e_per_segment = e_delta_total / num_segments if num_segments > 0 else 0.0
        is_travel = e_delta_total <= 0.0

        # Z interpolation
        z_start = self.current_z
        z_per_segment = (target_z - z_start) / num_segments if num_segments > 0 else 0.0

        waypoints = []
        feed_rate = self.current_f * MM_PER_MIN_TO_M_PER_S

        for seg in range(1, num_segments + 1):
            frac = seg / num_segments
            if clockwise:
                angle = start_angle - sweep * frac
            else:
                angle = start_angle + sweep * frac

            seg_x = center_x + radius * math.cos(angle)
            seg_y = center_y + radius * math.sin(angle)
            seg_z = z_start + z_per_segment * seg

            # Compute extrusion rate for this segment
            extrusion_rate = 0.0
            if e_per_segment > 0:
                seg_dist = self.arc_resolution  # approximate
                feed_mm_per_s = self.current_f / 60.0
                volume_mm3 = e_per_segment * self.filament_area
                move_time = seg_dist / feed_mm_per_s if feed_mm_per_s > 0 else 0.0
                if move_time > 0:
                    extrusion_rate = (volume_mm3 * 1e-9) / move_time

            wp = Waypoint(
                position=np.array([
                    seg_x * MM_TO_M,
                    seg_y * MM_TO_M,
                    seg_z * MM_TO_M,
                ]),
                feed_rate=feed_rate,
                extrusion_rate=extrusion_rate,
                is_travel=is_travel,
                layer_index=self.current_layer,
                line_number=line_num,
            )
            waypoints.append(wp)

        self.current_x = target_x
        self.current_y = target_y
        self.current_z = target_z

        return waypoints

    def _handle_home(self, params: Dict[str, float], line_num: int) -> List[Waypoint]:
        """Handle G28 home command."""
        self.current_x = 0.0
        self.current_y = 0.0
        self.current_z = 0.0
        wp = Waypoint(
            position=np.array([0.0, 0.0, 0.0]),
            feed_rate=self.default_feed_rate * MM_PER_MIN_TO_M_PER_S,
            is_travel=True,
            layer_index=self.current_layer,
            line_number=line_num,
        )
        return [wp]

    def _handle_set_position(self, params: Dict[str, float]):
        """Handle G92 set position command."""
        if 'X' in params:
            self.current_x = params['X']
        if 'Y' in params:
            self.current_y = params['Y']
        if 'Z' in params:
            self.current_z = params['Z']
        if 'E' in params:
            self.current_e = params['E']

    def _build_toolpath(self, waypoints: List[Waypoint], metadata: Dict) -> Toolpath:
        """Organize flat waypoint list into layers."""
        if not waypoints:
            return Toolpath(metadata=metadata)

        # Group by layer_index
        layer_map: Dict[int, List[Waypoint]] = {}
        for wp in waypoints:
            layer_map.setdefault(wp.layer_index, []).append(wp)

        layers = []
        sorted_indices = sorted(layer_map.keys())

        for i, layer_idx in enumerate(sorted_indices):
            layer_wps = layer_map[layer_idx]
            z_height = layer_wps[0].z if layer_wps else 0.0

            # Compute layer height from Z difference
            layer_height = 0.0
            if i > 0:
                prev_z = layers[-1].z_height
                layer_height = z_height - prev_z
            elif z_height > 0:
                layer_height = z_height  # First layer height

            layer = Layer(
                index=layer_idx,
                z_height=z_height,
                waypoints=layer_wps,
                layer_height=layer_height,
            )
            layers.append(layer)

        # Store temperature metadata
        if self.temperatures:
            metadata['temperatures'] = dict(self.temperatures)

        return Toolpath(layers=layers, metadata=metadata)
