# Copyright 2024 Kevin Medrano
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for G-code parser."""

import pytest

from ur_3d_printer.gcode_parser import GCodeParser, MM_TO_M, MM_PER_MIN_TO_M_PER_S


SAMPLE_GCODE = """\
; Generated by TestSlicer
; Layer height: 0.2
G28 ; Home
G90 ; Absolute positioning
M82 ; Absolute extrusion
G92 E0 ; Reset extruder
M104 S200 ; Set hotend temp
M109 S200 ; Wait for hotend temp
; Layer 0
G1 Z0.2 F600 ; Move to first layer
G1 X10 Y10 F1200 E0.5 ; Print move
G1 X20 Y10 E1.0
G1 X20 Y20 E1.5
G1 X10 Y20 E2.0
G1 X10 Y10 E2.5
G0 X0 Y0 F3000 ; Travel
; Layer 1
G1 Z0.4 F600
G1 X10 Y10 F1200 E3.0
G1 X20 Y10 E3.5
G1 X20 Y20 E4.0
G1 X10 Y20 E4.5
G1 X10 Y10 E5.0
"""

RELATIVE_GCODE = """\
G91 ; Relative positioning
M83 ; Relative extrusion
G1 X10 Y0 F1200 E0.5
G1 X0 Y10 E0.5
G1 X-10 Y0 E0.5
"""

ARC_GCODE = """\
G90
G1 X10 Y0 Z0.2 F1200
G2 X0 Y10 I-10 J0 E1.0
"""


class TestGCodeParser:
    def test_parse_sample(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        # Should have layers (layer 0 + layer 1 + initial Z-move layer)
        assert tp.num_layers >= 2
        assert tp.num_waypoints > 0

    def test_positions_converted_to_meters(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        all_wp = tp.all_waypoints
        # Find a waypoint at X=10mm = 0.01m
        x10_wps = [w for w in all_wp if abs(w.x - 0.01) < 1e-6]
        assert len(x10_wps) > 0

    def test_feed_rate_converted_to_m_per_s(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        all_wp = tp.all_waypoints
        # F1200 mm/min = 0.02 m/s
        f1200_wps = [w for w in all_wp if abs(w.feed_rate - 1200 * MM_PER_MIN_TO_M_PER_S) < 1e-6]
        assert len(f1200_wps) > 0

    def test_travel_detection(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        all_wp = tp.all_waypoints
        travel_wps = [w for w in all_wp if w.is_travel]
        extrusion_wps = [w for w in all_wp if not w.is_travel]
        assert len(travel_wps) > 0
        assert len(extrusion_wps) > 0

    def test_layer_detection(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        # Should detect at least 2 layers from Z changes
        assert tp.num_layers >= 2

        # Layer Z heights should be increasing
        z_heights = [layer.z_height for layer in tp.layers]
        for i in range(1, len(z_heights)):
            assert z_heights[i] >= z_heights[i - 1]

    def test_extrusion_rate(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        # Extruding waypoints should have positive extrusion rate
        for wp in tp.all_waypoints:
            if not wp.is_travel and wp.extrusion_rate > 0:
                assert wp.extrusion_rate > 0
                break
        else:
            pytest.fail("No waypoint with positive extrusion rate found")

    def test_relative_positioning(self):
        parser = GCodeParser()
        tp = parser.parse_lines(RELATIVE_GCODE.splitlines())

        all_wp = tp.all_waypoints
        assert len(all_wp) == 3

        # After G91: X10 -> X10+0 -> X10-10=0
        assert all_wp[0].x == pytest.approx(10 * MM_TO_M)
        assert all_wp[1].x == pytest.approx(10 * MM_TO_M)
        assert all_wp[2].x == pytest.approx(0.0)

        # Y: 0 -> 10 -> 10
        assert all_wp[1].y == pytest.approx(10 * MM_TO_M)

    def test_arc_discretization(self):
        parser = GCodeParser(arc_resolution=1.0)
        tp = parser.parse_lines(ARC_GCODE.splitlines())

        all_wp = tp.all_waypoints
        # Should have the G1 move + multiple arc segments
        assert len(all_wp) > 3

        # Arc should end near (0, 10mm) = (0, 0.01m)
        last_arc = all_wp[-1]
        assert last_arc.x == pytest.approx(0.0, abs=0.001)
        assert last_arc.y == pytest.approx(0.01, abs=0.001)

    def test_g92_set_position(self):
        lines = [
            "G90",
            "G1 X10 Y10 Z0.2 F1200 E1.0",
            "G92 E0",  # Reset E
            "G1 X20 Y10 E0.5",  # 0.5mm of extrusion from reset
        ]
        parser = GCodeParser()
        tp = parser.parse_lines(lines)
        assert tp.num_waypoints == 2

    def test_home_command(self):
        lines = ["G28"]
        parser = GCodeParser()
        tp = parser.parse_lines(lines)

        assert tp.num_waypoints == 1
        wp = tp.all_waypoints[0]
        assert wp.x == pytest.approx(0.0)
        assert wp.y == pytest.approx(0.0)
        assert wp.z == pytest.approx(0.0)
        assert wp.is_travel is True

    def test_metadata_extraction(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        # Should extract slicer and layer height from comments
        assert 'generated_by' in tp.metadata or 'layer_height' in tp.metadata

    def test_temperature_metadata(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        assert 'temperatures' in tp.metadata
        assert tp.metadata['temperatures']['hotend'] == 200.0

    def test_empty_input(self):
        parser = GCodeParser()
        tp = parser.parse_lines([])
        assert tp.num_layers == 0
        assert tp.num_waypoints == 0

    def test_comments_only(self):
        parser = GCodeParser()
        tp = parser.parse_lines(["; just a comment", "; another comment"])
        assert tp.num_waypoints == 0

    def test_line_numbers_preserved(self):
        parser = GCodeParser()
        tp = parser.parse_lines(SAMPLE_GCODE.splitlines())

        for wp in tp.all_waypoints:
            assert wp.line_number > 0
